image: continuumio/miniconda3:latest

variables:
  GIT_SSL_NO_VERIFY: "0"
  GIT_DEPTH: "10"

before_script:
  - git --version

pages:
  script:
  - conda env create -f environment.yml
  - make html
  - mv build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
