image: continuumio/miniconda3:latest

variables:
  GIT_SSL_NO_VERIFY: "1"
  DEPTH: "10"

pages:
  script:
  - conda env create -f environment.yml
  - make html
  - mv build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
