image: continuumio/miniconda3:latest

variables:
  GIT_SSL_NO_VERIFY: "1"

before_script:
  - git --version

pages:
  script:
  - conda env create -f environment.yml
  - conda install -c anaconda make
  - cd remo2-doc
  - make html
  - mv build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
